[tool.poetry]
name = "estrotracker"
version = "0.1.0"
description = ""
authors = ["Sam Johnson <sambjohnson94@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
flask = "^3.0.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
